
        <table>
            <tr>
                <td>Manufacturer name :</td>
                <td><input id="name" type="text" placeholder="enter name"></td>
            </tr>
            <tr>
                <td>Enable</td>
                <td><input id="enabled" type="checkbox"></td>
            </tr>
            <tr>
                <td>Street address</td>
                <td><input id="address_street" type="text" placeholder="street address"></td>
            </tr>
            <tr>
                <td>City</td>
                <td><input id="city" type="text" placeholder="city name"></td>
            </tr>
            <tr>
                <td>Country</td>
                <td><input id="country" type="text"></td>
            </tr>
            <tr>
                <td>Contact name</td>
                <td><input id="contact_name" type="text"></td>
            </tr>
            <tr>
                <td>Contact phone</td>
                <td><input id="contact_phone" type="text" placeholder=""></td>
            </tr>
        </table>
        <input type="submit" onclick="getManufacturer()">
    <div id="result">
        <div>
            <p class="name"></p>
            <p class="enabled"></p>
            <p class="address_street"></p>
            <p class="address_city"></p>
            <p class="address_country"></p>
        </div>
    </div>
        <script type="text/javascript">
            function getData() {
                alert("xxx");
            }
            function getManufacturer()
            {
                var a=1;
                console.log(a);
                var name = document.getElementById("name").value;
                var enabled = document.getElementById("enabled").checked;
                var address_street = document.getElementById("address_street").value;
                var address_city = document.getElementById("city").value;
                var address_country = document.getElementById("country").value;
                var contact_name = document.getElementById("contact_name").value;
                var contact_phone = document.getElementById("contact_phone").value;
                data = jQuery(this).serialize();
                    jQuery.ajax(
                        {
                            type: "POST",
                            dataType: "json",
                            showLoader: true,
                            url: "manufacturer/manufacturer",
                            data: {name: name,
                                enabled: enabled,
                                address_street:address_street,
                                address_city:address_city,
                                address_country:address_country,
                                contact_name:contact_name,
                                contact_phone:contact_phone
                            },
                        }
                    ).done(function (response) {
                               for(var i=0; i<response.length;i++)
                               {
                                   var tex= response[i].name;
                                   var str='<p class="name"> phone: '+response[i].contact_phone+'</p><p class="enabled"></p><p class="address_street"></p><p class="address_city"></p><p class="address_country"></p>';
                                   var temp = document.createElement('div');
                                   temp.innerHTML = str;
                                   jQuery('#result').add(str);
                                    console.log(i);
                                    console.log(response[i]['name']);
                               }

                    });
            }
        </script>