

<table>
    <tr>
        <td>Title:</td>
        <td><input type="text" ></td>
    </tr>
    <tr>
        <td>commission:</td>
        <td><input type="text" ></td>
    </tr>
    <tr>
        <td>bride_firstname:</td>
        <td><input type="text" ></td>
    </tr>
    <tr>
        <td>bride_lastname:</td>
        <td><input type="text" ></td>
    </tr>
    <tr>
        <td>bride_email:</td>
        <td><input type="text" ></td>
    </tr>
    <tr>
        <td>sent_to_bride:</td>
        <td><input type="text" ></td>
    </tr>
    <tr>
        <td>groom_firstname:</td>
        <td><input type="text" ></td>
    </tr>
    <tr>
        <td>groom_lastname:</td>
        <td><input type="text" ></td>
    </tr>
    <tr>
        <td>groom_email:</td>
        <td><input type="text" ></td>
    </tr>
    <tr>
        <td>sent_to_groom:</td>
        <td><input type="text" ></td>
    </tr><tr>
        <td>message:</td>
        <td><input type="text" ></td>
    </tr>
</table>