<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$manufacturer = $objectManager->create('Mgn\Cybergame\Model\ResourceModel\RomExtraOption\CollectionFactory');
$result = $manufacturer->create()->getData();
?>
<table>
    <tr>
        <th>ProductId</th>
        <th>PC Number</th>
        <th>Price</th>
        <th>Action</th>
    </tr>
    <?php foreach ($result as $item){
        $price= $item['food_price']+$item['drink_price'];
        ?>
        <tr>
            <td><input style="border: none"  type="text" id="product" value="<?php echo $item['id']?>" readonly></td>
            <td><input type="text" id="numberPc" value="<?php echo $item['number_pc']?>" readonly></td>
            <td><input type="text" id="price" value="<?php echo $price?>" readonly></td>
            <td><a id="edit" onclick="editRoom()">Edit</a></td>
        </tr>
    <?php }?>
</table>
<script type="text/javascript">
    function check() {
        alert('1');
    }
    function editRoom(){
        var check=jQuery("#edit").text();
        if(check==='Edit') {
            jQuery('input').attr('readonly', false);
            jQuery("#edit").text('Save');
            jQuery("product").focus();
        }
        else{
            var product = document.getElementById("product").value;
            var numberPc = document.getElementById("numberPc").value;
            var price = document.getElementById("price").value;

            jQuery.ajax(
                {
                    type: "POST",

                    dataType: "json",
                    showLoader: true,
                    url: "<?php echo $block->getUrl('cybergame/updaterominfo/edit'); ?>",
                    data: {product: product,numberPc:numberPc,price:price} /**/
                }
            ).done(function (response) {
                jQuery('input').attr('readonly', true);
                jQuery("#edit").text('Edit');
            });
        }
    }
</script>
